fix: run script directly

diff --git a/.github/actions/run-unit-tests/action.yml b/.github/actions/run-unit-tests/action.yml
--- a/.github/actions/run-unit-tests/action.yml
+++ b/.github/actions/run-unit-tests/action.yml
@@ -16,7 +16,21 @@ runs:
 
     - name: Verify at least one test has run
       shell: bash
-      run: .github/scripts/verify-unit-test-run.sh
+      run: |
+        #!/bin/bash
+        total_count=0
+        while read file; do
+          count=$(xpath -q -e "//TestRun/ResultSummary/Counters/@total" "$file" 2>/dev/null | cut -d'"' -f2)
+          echo "$file: $count tests executed"
+          total_count=$((total_count + count))
+        done < <(find tests -name "*.trx")
+          
+        if [ $total_count -le 0 ]; then
+          echo "Error: No unit tests have been executed."
+          exit 1
+        else
+          echo "Total tests executed: $total_count"
+        fi
 
     - name: Test Report
       uses: dorny/test-reporter@v1
