revert all changes

diff --git a/.github/workflows/code-pr-check.yml b/.github/workflows/code-pr-check.yml
--- a/.github/workflows/code-pr-check.yml
+++ b/.github/workflows/code-pr-check.yml
@@ -23,16 +23,97 @@ env:
 jobs:
   build-test-web-app:  
     name: Build and run unit tests
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
 
     steps:
       - name: Check out repository
         uses: actions/checkout@v3
 
-      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
-        uses: actions/setup-dotnet@v3
+      - name: Cache SonarCloud packages
+        uses: actions/cache@v1
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
+          path: ~\sonar\cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
 
-      - name: Build project
-        run: dotnet build ./src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj 
+      - name: Install dotnet coverage
+        run: dotnet tool install --global dotnet-coverage
+  
+      - name: Install SonarCloud scanners
+        run: dotnet tool install --global dotnet-sonarscanner
+
+      - name: Start SonarCloud scanner
+        run: |
+          dotnet-sonarscanner begin \
+            /k:"DFE-Digital_plan-technology-for-your-school" \
+            /o:"dfe-digital" \
+            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
+            /d:sonar.host.url="https://sonarcloud.io" \
+            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
+            /d:sonar.coverage.exclusions=src/**/Program.cs,src/Dfe.PlanTech.Web/gulpfile.js,src/Dfe.PlanTech.Web/wwwroot/** \
+            /d:sonar.issue.ignore.multicriteria=e1 \
+            /d:sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S6602 \
+            /d:sonar.issue.ignore.multicriteria.e1.resourceKey=src/**/*.cs
+          
+      - name: Build web app  
+        uses: ./.github/actions/build-dotnet-app
+        with:
+          dotnet_version: ${{ env.DOTNET_VERSION }}  
+          solution_filename: plan-technology-for-your-school.sln
+
+      - name: Run unit tests
+        uses: ./.github/actions/run-unit-tests
+        with:
+          solution_filename: plan-technology-for-your-school.sln
+
+      - name: Merge test results
+        run: dotnet-coverage merge -f xml -o "coverage.xml" -s "coverage.settings.xml" -r coverage.cobertura.xml
+
+      - name: End SonarCloud Scanner
+        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+
+      - name: Archive code coverage results
+        uses: actions/upload-artifact@v3
+        with:
+          name: code-coverage-report
+          path: coverage.xml
+
+  build-database-upgrader:  
+    name: Build database upgrader
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v3
+
+      - name: Build database upgrader  
+        uses: ./.github/actions/build-dotnet-app
+        with:
+          dotnet_version: ${{ env.DOTNET_VERSION }}  
+          solution_filename: Dfe.PlanTech.DatabaseUpgrader.sln
+
+  run-javascript-tests:
+    runs-on: ubuntu-latest
+    name: Run javascript tests
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "latest"
+
+      - name: Install Dependencies
+        run: npm install
+
+      - name: Run the tests
+        run: npm test
+
+      - name: Test report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: ./junit.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
