cicd: update dotnet versions for workflows

diff --git a/.github/workflows/code-pr-check.yml b/.github/workflows/code-pr-check.yml
--- a/.github/workflows/code-pr-check.yml
+++ b/.github/workflows/code-pr-check.yml
@@ -1,34 +1,33 @@
-name: Code PR Check 
+name: Code PR Check
 
 on:
   push:
     branches: ["main", "development"]
     paths:
-      - 'src/**'
-      - 'tests/**'
+      - "src/**"
+      - "tests/**"
   pull_request:
     branches: ["main", "development"]
     paths:
-      - 'src/**'
-      - 'tests/**'
-      - '.github/workflows/code-pr-check.yml'
+      - "src/**"
+      - "tests/**"
+      - ".github/workflows/code-pr-check.yml"
 
 concurrency:
-  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
+  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
   cancel-in-progress: true
-  
+
 env:
   DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}
-  
-jobs:
 
+jobs:
   get-src-dir-list:
     name: Get Directories for Linting
     runs-on: ubuntu-22.04
     if: ${{ github.event_name == 'pull_request' }}
     outputs:
       directories: ${{ steps.list-dir.outputs.directories }}
-    
+
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
@@ -54,14 +53,13 @@ jobs:
       pull-requests: write
 
     steps:
-
       - name: Checkout Repository
         uses: actions/checkout@v3
 
       - name: Set up .NET
         uses: actions/setup-dotnet@v3
         with:
-          dotnet-version: ${{ env.DOTNET_VERSION }}
+          dotnet-version: 8.0.x
           cache: false
         env:
           DOTNET_INSTALL_DIR: "/usr/share/dotnet"
@@ -79,7 +77,7 @@ jobs:
           commit: true
           github_token: ${{ secrets.GITHUB_TOKEN }}
 
-  build-test-web-app:  
+  build-test-web-app:
     name: Build and run unit tests
     runs-on: ubuntu-22.04
     if: ${{ always() && ( github.event_name == 'pull_request' && needs.lint-code.result == 'success' ) || ( github.event_name == 'push' && needs.lint-code.result == 'skipped' ) }}
@@ -98,16 +96,16 @@ jobs:
 
       - name: Install dotnet coverage
         run: dotnet tool install --global dotnet-coverage --version 17.9.3
-  
+
       - name: Install SonarCloud scanners
         run: dotnet tool install --global dotnet-sonarscanner
 
       - name: Install latest JDK
         uses: actions/setup-java@v3
         with:
-          distribution: 'microsoft'
-          java-version: '17'
-          
+          distribution: "microsoft"
+          java-version: "17"
+
       - name: Start SonarCloud scanner
         run: |
           dotnet-sonarscanner begin \
@@ -120,11 +118,11 @@ jobs:
           /d:sonar.issue.ignore.multicriteria=e1 \
           /d:sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S6602 \
           /d:sonar.issue.ignore.multicriteria.e1.resourceKey=src/**/*.cs
-      
-      - name: Build web app  
+
+      - name: Build web app
         uses: ./.github/actions/build-dotnet-app
         with:
-          dotnet_version: ${{ env.DOTNET_VERSION }}  
+          dotnet_version: ${{ env.DOTNET_VERSION }}
           solution_filename: plan-technology-for-your-school.sln
 
       - name: Run unit tests
@@ -144,7 +142,7 @@ jobs:
           name: code-coverage-report
           path: coverage.xml
 
-  build-database-upgrader:  
+  build-database-upgrader:
     name: Build database upgrader
     runs-on: ubuntu-22.04
 
@@ -152,10 +150,10 @@ jobs:
       - name: Check out repository
         uses: actions/checkout@v3
 
-      - name: Build database upgrader  
+      - name: Build database upgrader
         uses: ./.github/actions/build-dotnet-app
         with:
-          dotnet_version: ${{ env.DOTNET_VERSION }}  
+          dotnet_version: ${{ env.DOTNET_VERSION }}
           solution_filename: Dfe.PlanTech.DatabaseUpgrader.sln
 
   run-javascript-tests:
@@ -178,8 +176,8 @@ jobs:
 
       - name: Test report
         uses: dorny/test-reporter@v1
-        if: success() || failure()    # run this step even if previous step failed
+        if: success() || failure() # run this step even if previous step failed
         with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: ./junit.xml    # Path to test results
-          reporter: jest-junit        # Format of test results
+          name: JEST Tests # Name of the check run which will be created
+          path: ./junit.xml # Path to test results
+          reporter: jest-junit # Format of test results
